version: "3.9"

services:
  auth_server:
    image: docker.io/sebastian992/auth_server
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    env_file:
      - .env
    expose:
      - "5433"
    ports:
      - 5433:5433
    command: -p 5433
